### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/factory-muffin#269]
We're still getting 2 or 3 times as many installs via the old package name! We need to do something about this.

@Zizaco Can you mark your package as "abandoned" on packagist, and point to the new one please?

**Comment by scottrobertson** [comment]
ping @Zizaco

**Comment by GrahamCampbell** [comment]
> Zizaco was unassigned by GrahamCampbell 4 hours ago

What? How did that happen? I wasn't anywhere near github 4 hours ago???

**Comment by scottrobertson** [comment]
@GrahamCampbell i thought that too, it happened when i added my comment. No idea.

**Comment by GrahamCampbell** [comment]
Also I doubt @Zizaco will ever respond to this. We need to find a better way to contact him.

**Comment by Zizaco** [comment]
Sorry! I'm gonna do it now!

**Comment by Zizaco** [comment]
Done :+1:

**Comment by GrahamCampbell** [comment]
Thanks. :)
