### ISSUE TITLE
Using factory-muffin with data-mapper

### ISSUE THREAD

**Issue by fesor** [thephpleague/factory-muffin#289]
In readme there is one strange line

> It's basically a "factory_girl", simplified for use with PHP.

But this library seems to be working only with Laravel's Active Record models. Do you have any plans to make it usable with Doctrine?

**Comment by joshhornby** [comment]
@kirkbushell Did you make any progress with this? Would love to use Factory Muffin with Doctrine.

**Comment by GrahamCampbell** [comment]
@joshhornby This was implemented already by @DavertMik, and is available in 3.x.

**Comment by joshhornby** [comment]
@GrahamCampbell Brilliant! Is there any docs on this yet?

**Comment by GrahamCampbell** [comment]
Sorry, there are no docs, but reading over the tests might help. I have no time to write any decent upgrading docs, or usage docs for the doctrine stuff, sorry.

**Comment by joshhornby** [comment]
No worries, I will look over the tests. Thank you for the quick response :+1:
