### ISSUE TITLE
Video Tutorials

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/factory-muffin#378]
I think video tutorials for factory muffin 3.0 might be very appealing to both newcomers, and existing 2.1 users.

**Comment by saada** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
I'll be recording these in July/August 2015 btw. I have no time this time of year. I'll also be cleaning up the docs and writing an upgrading guide, and releasing 3.0 then.
