### ISSUE TITLE
Include autoincrement number for (better) UUID support

### ISSUE THREAD

**Issue by canfiax** [thephpleague/factory-muffin#382]
When defining a muffin, I'd like to be able to define a value that is auto incremented. For instance; I make use of UUID, and when writing tests, it could be very useful to be able to call users like this: 1, 2, 3,4.

I.e:

	FactoryMuffin::define(
	    'User', [
	    	'id'    	    	    	=> 'autoincrement', // would produce: 1, 2, 3, 4, 5, etc for each muffin
	    	'firstname'		=> 'string',
	    	'lastname'			=> 'string',
	    	'email' 			=> 'email',
	        'size_system'      	=> 'numberBetween|1;7',
	    ]
	);

Is this possible as of right now?

**Comment by scottrobertson** [comment]
@GrahamCampbell FactoryGirl has an idea of Sequences, it's maybe something we can implement:

```ruby
FactoryGirl.define do
  factory :user do
    sequence(:email) { |n| "user#{n}@romhut.com"}
  end
end
```

```ruby
FactoryGirl.define do
  factory :user do
    sequence(:id) { |n| n}
  end
end
```

**Comment by scottrobertson** [comment]
@canfiax as a work around, you could use a combination of fakers `unique()` and `randomDigitNotNull()`

**Comment by GrahamCampbell** [comment]
This is already possible using our callable generator.

**Comment by GrahamCampbell** [comment]
Just pass in something like this:

```php
function () use ($gen) {
    $gen->next();
};
```

Where the `$gen` variable is an instance of a class that looks like this:

```php
class Gen
{
    private $last = 0;

    public function next()
    {
        return ++$this->last;
    }
}
```

**Comment by GrahamCampbell** [comment]
Or, even just this:

```php
function () {
    static $last;
    
    if ($last === null) {
        return $last = 1;
    }
    
    return ++$last;
};
```

**Comment by sharan1** [comment]
@GrahamCampbell I recently updated factory muffin from v2.1 to v3.1 

For auto-incrementing ids, we used to use the following function:

```
function () {
    static $last;

    function () {
        static $last;if ($last === null) {
        return $last = 1;
    }

    return ++$last;
};
```

But after upgrading the same function always started returning `1`, resulting in errors for duplication of primary key in our test database. 

Any idea what could be the issue and how to resolve it?
