### ISSUE TITLE
[3.0] Any updated? 

### ISSUE THREAD

**Issue by DavertMik** [thephpleague/factory-muffin#387]
Didn't hear for a long time about updated on 3.0
If the beta and docs are ready not sure what stops you to publish 3.0 release :)

3.0 api looks promising and I'd like to recommend Codeception users to use FactoryMuffin in their tests.

**Comment by GrahamCampbell** [comment]
3.0 will be released at the very end of June.

**Comment by GrahamCampbell** [comment]
I want to make sure the docs are as complete as the 1.x->2.x docs where for upgrading, and that the new 3.x docs are really easy to read. I also plan to record a couple of tutorial videos, though they'll probably come later. My aim is to ship 3,0 as soon as I have the time to do it. :)

**Comment by GrahamCampbell** [comment]
We're also waiting on the release of faker 1.5. :)

**Comment by DavertMik** [comment]
Ok, sounds great. Will be waiting for that moment! I plan to built Codeception module for FactoryMuffin by that time. Thanks!

**Comment by GrahamCampbell** [comment]
@DavertMik That sounds totally awesome. I'll deffo check it out. :)
