### ISSUE TITLE
Possible date of 3.0.0 being stable?

### ISSUE THREAD

**Issue by jdgriffith** [thephpleague/factory-muffin#395]
Looking to find out when 3.0.0 will be stable. Would really like to use this version at work. Appears it has a better understanding of definitions. Thanks!

**Comment by GrahamCampbell** [comment]
It's essentially done, I just don't have time to finish the docs atm. It's stable, so feel free to use it. If your not upgrading from 2.x, then the docs are done, the upgrading docs are just poor atm.

**Comment by jdgriffith** [comment]
Ok sweet! Thank you for the quick response.
