### ISSUE TITLE
Examples of 3.0.0 usage

### ISSUE THREAD

**Issue by jdgriffith** [thephpleague/factory-muffin#396]
Beginning to use 3.0.0 and I understand you don't have documentation yet. Any chance you have some working examples or simple prototypes though? I see where you have the callable maker argument in some places and would like to see how that is used in the new version. Thanks!

**Comment by GrahamCampbell** [comment]
All the docs on the readme are up to date for 3.0.

**Comment by GrahamCampbell** [comment]
We just haven't written the 2.x -> 3.0 upgrading guide yet.

**Comment by jdgriffith** [comment]
Ahh ok. Will look there. Thanks!

**Comment by GrahamCampbell** [comment]
Example 1 uses the callable generator btw. :)
