### ISSUE TITLE
factory-muffin ~3.0 and factory-muffin-faker ~1.0 fail composer install

### ISSUE THREAD

**Issue by ddinchev** [thephpleague/factory-muffin#398]
With the latest composer versions, trying to add `"league/factory-muffin": "~3.0"` to your `require-dev` section in `composer.json` would then fail `composer update`. Same goes for ~1.0 and the faker extension. The reason is the versions are not actually final.

Could you create final versions that include all patches released since the betas or hint in the article that those versions can be installed with version "dev-master@dev" instead of "~3.0"?

**Comment by GrahamCampbell** [comment]
Lower your global minimum stability.

**Comment by GrahamCampbell** [comment]
NEVER use dev-master.

**Comment by GrahamCampbell** [comment]
use `~3.0@dev` if you really want.

**Comment by ddinchev** [comment]
Thanks for the suggestion. Could you update that in the README, so that others don't get confused on why the suggested `composer.json` section does not work?
