### ISSUE TITLE
Allow to use optional modifier with factory

### ISSUE THREAD

**Issue by localheinz** [thephpleague/factory-muffin#401]
This currently fails:

```php
$factory->define(Model_Contest::class, [
    'sponsor_id' => 'optional:factory|' . Model_Contest_Sponsor::class,
]);
```

SQL ends up trying to insert the value `optional:factory` into the `sponsor_id` column.
This has been observed with 84e9807.

:information_desk_person: Can we make the `optional` modifier work with factories?

**Comment by GrahamCampbell** [comment]
3.x is now the only currently maintained series for anything but important fixes and security fixes.

**Comment by GrahamCampbell** [comment]
Thanks for your interest though.
