### ISSUE TITLE
Overwriting model attributes

### ISSUE THREAD

**Issue by JonoB** [thephpleague/factory-muffin#409]
Assuming we have a factory as follows:

```
$fm->define(\Category::class, [
    'code' => Faker::word(),
    'name' => Faker::sentence(),
]);
```

And in one of our tests we want to inject `companyId` property:
```
$category = $this->fm->create(\Category::class, [
     'company_id' => $companyId,
]);
```

In this case, if `$category->toArray()` looks like this:
```
[
  "company_id" => 1
  "id" => 1
]
```

Basically, the default proprties (`code` and `name`) are now gone. Why does injecting properties as the second parameter to `->create()` method completely replace all model properties? This doesn't seem to be expected behavior (or consistent with V2).

Am I missing something obvious here?

**Comment by GrahamCampbell** [comment]
I don't see how this could be happening?

https://github.com/thephpleague/factory-muffin/blob/master/src/FactoryMuffin.php#L181

**Comment by JonoB** [comment]
Yeah, its because our factories were set up V2 style:
```
$fm->define(\Category::class, [
    'code' => Faker::word(),
    'name' => Faker::sentence(),
]);
```
Instead, we need to be using the `setDefinitions` method:
```
$fm->define(Category::class)->setDefinitions([
    'code' => Faker::word(),
    'name' => Faker::sentence(),
]);
