### ISSUE TITLE
loadDirectory hitting dot-hidden directories

### ISSUE THREAD

**Issue by LostKobrakai** [thephpleague/factory-muffin#414]
I've added folder sharing to my vm and mac os is automatically creating .AppleDouble directories in each folder. FactoryMuffin is picking up on them, which results in invalid files being loaded. I've updated the regex statement, which filters the files:

```php
    private function loadDirectory($path)
    {
        $directory = new RecursiveDirectoryIterator($path);
        $iterator = new RecursiveIteratorIterator($directory);
        $files = new RegexIterator($iterator, '/^[^\.](?:(?!\/\.).)+?\.php$/i');

        $fm = $this;

        foreach ($files as $file) {
            require $file->getPathName();
        }
    }
```

Not sure if that's the correct way of going about it.

**Comment by GrahamCampbell** [comment]
Looks good to me.

**Comment by GrahamCampbell** [comment]
I've merged your suggestion.
