### ISSUE TITLE
FactoryMuffin loadDirectory filename regex does not seem to handle relative paths

### ISSUE THREAD

**Issue by Bouwdie** [thephpleague/factory-muffin#419]
Maybe the regex could be simpler as well? `[^\/]+\.php$`
https://regex101.com/r/rJ3hS9/1

**Comment by GrahamCampbell** [comment]
Relative file path are intentionally not supported.

**Comment by GrahamCampbell** [comment]
What was your use case?

**Comment by Bouwdie** [comment]
The use case was loading a factories folder directly under /test/factories from a test class 
/test/Ns1/xTest.php. Now i called realpath on the relative dir to get it working. Or update the regex to handle relative paths. Why is it intentionally not supported? ../../factories i understand, but /home/test/foo/../factories should work right?

**Comment by GrahamCampbell** [comment]
Hmmm, ok. Feel free to submit a pull request, and I'll take a look at it. ;)

**Comment by GrahamCampbell** [comment]
Ping @Bouwdie. ;)

**Comment by Bouwdie** [comment]
Will take a look at it real soon @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Closing due to no response from the OP.
