### ISSUE TITLE
Seed withoud save

### ISSUE THREAD

**Issue by Ricky-rick** [thephpleague/factory-muffin#436]
I have some models in my project that will be populated by a Api. These models don't have a save function. For that reason i use the 'instance' method to generate a model. But there is no method to seed with te instance function.

**Comment by GrahamCampbell** [comment]
How does https://github.com/thephpleague/factory-muffin/pull/437 look?

**Comment by Ricky-rick** [comment]
Great! This works for me.

**Comment by ctrlaltdylan** [comment]
Is there another method like `new` for just building a new model without persisting it?
