### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by kanariezwart** [thephpleague/factory-muffin#461]
Is there still active support for this library?
The documentation is outdated, and last commit is from aug 2017.

**Comment by pedro-stanaka** [comment]
@GrahamCampbell @nyamsprod can we somehow help?

**Comment by GrahamCampbell** [comment]
Yeh, this is still maintained. I am not aware of any bugs, which is why there have been no commits recently. I have not merged any new features as I want to consider them carefully first. Once I get some time, I will give feedback on the outstanding PRs. :)
