### ISSUE TITLE
FM tries to call string as a function if its the same name as a built-in

### ISSUE THREAD

**Issue by philhoughton** [thephpleague/factory-muffin#465]
Hello.

Firstly, thanks for this package. Hope the following has enough detail.

Had been getting a little irritated with an intermittent issue which I've found the time to investigate a bit. 

Every so often a field would get replaced with a non-string then when try to persist it would freak out with a 'Could not convert XX object to string' error. Turns out it was every time faker would generate 'Max' as a name. Digging in further it seems if you tried other built in function names (say 'Floor' or 'Abs' etc), it would also do it.

So say I was to do the following:

`
$factoryMuffin->create(\App\Entity\User::class, [
    'firstName' => 'Max'
]);
`

This would try and run max() which does all sorts of unpredictable things with the resulting object (in my particular instance a reference to the containing object).
 
I've created a repro [here](https://github.com/philhoughton/factory-muffin-repro) if that is helpful.

Digging in to this deeper, the culprit seems to be GeneratorFactory::make calling is_callable, which obviously returns true as 'max' is an OK function, but it is also a string. 

I can fix the issue by changing Line 57 to:
`if (!is_string($kind) && is_callable($kind) || is_string($kind) && strpos($kind, '::') !== false) `

The tests pass, but I'm not sure thats a great approach? And my use case doesn't really cover using FM with the scope resolving format like that, so don't know if I'm understanding why it should be used in that manner.

Happy to attempt a pull request (never done one) if you like and are feeling patient.

**Comment by GrahamCampbell** [comment]
Thanks for the detailed description. I don't think we can fix this without breaking a lot of stuff for people, since your proposed fix would break any code that used function names as callables.

Instead, I'd suggest you do the following in your code to work around this limitation:

```php
$factoryMuffin->create(\App\Entity\User::class, [
   'firstName' => function () { return 'Max'; }
]);
```

**Comment by philhoughton** [comment]
Suspect you're probably right on the fixing part. Thinking a bit more about it, I'm not sure it would be possible to reliably tell what a built-in function vs some other callable is, especially if its a global func.

That work around works well enough for me for the moment. 

Thanks.
