### ISSUE TITLE
Add warning to docs that you can't use your own Faker instance

### ISSUE THREAD

**Issue by igorsantos07** [thephpleague/factory-muffin#467]
My tests already had a custom Faker installation, but it's not obvious from the docs you _must_ use the facade, otherwise, you'll get duplicated entries.

> And no need to suggest "we accept PRs", I'm posting this as an up for grabs. I may come back if I get some free time, as this lib seems useful and is definitely needing some love, but I definitely can't guarantee.

Speaking of PRs btw, #426 is definitely lacking.

**Comment by GrahamCampbell** [comment]
> but it's not obvious from the docs you must use the facade, otherwise, you'll get duplicated entries.

That's not true. You just need to persist your instance between tests...

**Comment by igorsantos07** [comment]
So this is, at the very least, a Codeception bug. I'll check what they do
with your library, then, as I guess you're not interested in debugging.

Nonetheless, if someone noticed that, why not mentioning this in docs
instead of straight out closing the issue?

Not sure if I'm the doc freak or you're the careless undocumenter.

**Comment by GrahamCampbell** [comment]
It is not a bug in codeception. It's a big in your test. If you make a new instance each time, of course it doesn't know about what has been generated in the past...
