### ISSUE TITLE
Add warning to docs that you can't use your own Faker instance

### ISSUE THREAD

**Issue by igorsantos07** [thephpleague/factory-muffin#468]
Yep, I'm duplicating #467 because, besides closing without even understanding what was going on, you locked it without understanding further what was going on. Seriously??

My test just uses haveMultiple() from Codeception, so you have to decide if the issue is "you have to persist your instance between tests" or not. Again, you didn't care to read what I wrote.
The factory I had was using a fixed instance of Faker, instead of your facade. Then I saw the facade is actually a closure wrapper for Faker and I got why my factory wasn't working. 

Thus, as I said in the first post and you didn't care, the facade IS required. Otherwise, why wrap everything in closures for later consumption?

**Comment by GrahamCampbell** [comment]
You can use your own faker and the facade is not required. What more can I say. I've done it myself, without using the facade!

**Comment by GrahamCampbell** [comment]
Make a static property in your test class and set the faker instance there.

**Comment by GrahamCampbell** [comment]
The facade is just doing this for you with a fixed instance, but you can simulate this yourself, for your own custom needs...

**Comment by GrahamCampbell** [comment]
The reason I provided a facade was to help people to not make this kind of mistake.

**Comment by GrahamCampbell** [comment]
If there is a specific aspect of the docs you'd like to change, I'd of course consider any PR.

**Comment by igorsantos07** [comment]
Here's a sample code that triggers the issue I'm talking about:

```php
//this was actually defined in the tests bootstrap file, with other stuff
$faker = \Faker\Factory::create();

// _factories/entry.php
$fm->define('entry')->setDefinitions([
    'uuid'        => $faker->unique()->asciify(str_repeat('*', 15)),
    'code'        => $faker->unique()->randomNumber(),
    'description' => $faker->sentence()
]);

//then, in a test:
$I->haveMultiple('entry', 3); //creates three of the same values, or triggers a constraint violation for duplicated keys
```

So, if you say there _is_ a mistake, then there's something that can be improved in the docs, like "you should use the Facade or use your own Faker instance this and that, otherwise you'll get duplicated entries".

With a simple thing like that I was really considering sending a PR directly, but I'm not big on the project yet, so I had no idea what to write exactly in the first place. I even mentioned I was considering coming back, but the main intention was to post it for discussion of the issue and leave it for someone to fix (the docs), if you don't intend to.

**Comment by GrahamCampbell** [comment]
Ah, it's all coming back to me now. I too also don't know this codebase (anymore). This happening because you need to wrap the random number thing in a closure, otherwise you are genuinely just generating the number once, and using it three times.

**Comment by GrahamCampbell** [comment]
Replace `$faker->unique()->asciify(str_repeat('*', 15))` with `function () { return $faker->unique()->asciify(str_repeat('*', 15)); }`, etc. Or you can use the short closure syntax on newer PHP.

**Comment by igorsantos07** [comment]
Yep, that made sense once I saw what the Facade was about - initially I just thought it was a novel way to use singletons haha

Now that we finally understood what the issue was about, I'll write a PR later to get it explained in the README (probably next week, as I'm already done with the project that triggered that).

**Comment by GrahamCampbell** [comment]
> Yep, that made sense once I saw what the Facade was about - initially I just thought it was a novel way to use singletons haha

Yep, it does both of those things. I think https://github.com/thephpleague/factory-muffin-faker/pull/10 was only confusing. I was pressured to merge it, even though it was incorrect, and after a couple of years away from it, I didn't notice.
